// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "5e8f0315-9885-46fe-9337-757bf85da4fe");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1646789692);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1656562390);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1656562385);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1656562412);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1646789722);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{46b82071-d572-4bb0-9533-2f3fa3d345dd}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1646789662);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 127);
user_pref("browser.newtabpage.activity-stream.impressionId", "{43460e74-cc7f-47bf-8f43-2c4888b64245}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1646789666);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1656562397487");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1656564196487");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1656562398611");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1656583998611");
user_pref("browser.search.region", "KR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220608170832");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1656562388");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220608170832");
user_pref("browser.startup.homepage_override.mstone", "101.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1656562385);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1646789667460");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "101.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "KR");
user_pref("dom.push.userAgentID", "b03df058115742a78e9ea9f0a049ebcd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1656562383);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220608170832");
user_pref("extensions.lastAppVersion", "101.0.1");
user_pref("extensions.lastPlatformVersion", "101.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c8e45366-ac47-4d6f-8b9a-65991982c611\",\"formautofill@mozilla.org\":\"8481acf3-a06f-406f-b043-dc6345cc1965\",\"pictureinpicture@mozilla.org\":\"89a0e4b5-b84a-44aa-b05e-8312acf0e7a4\",\"screenshots@mozilla.org\":\"10d83691-36a1-4dbb-bdb8-1a72f3679ac2\",\"webcompat-reporter@mozilla.org\":\"2ed8d030-eef4-4bc2-831d-4747ddbcb008\",\"webcompat@mozilla.org\":\"d91e84c0-df30-4f9c-82be-a8812b005e51\",\"default-theme@mozilla.org\":\"041e3929-2c68-41ca-93c3-1dbe1a389ced\",\"addons-search-detection@mozilla.com\":\"7a1d24c7-7ba4-4cde-957a-b7dd6902e575\",\"google@search.mozilla.org\":\"b3ed3465-bd8a-45a5-ab1c-c75718c59d9a\",\"daum-kr@search.mozilla.org\":\"c043d32d-0cfb-44c7-bdcf-ece6d11d070a\",\"wikipedia@search.mozilla.org\":\"6e5778ee-05e9-4623-9b90-d0646d6b346d\",\"naver-kr@search.mozilla.org\":\"d216fe96-728f-442c-9098-ee0f0460a321\",\"ddg@search.mozilla.org\":\"7ff640f4-d904-4ec7-870b-d1b29d8bb5ed\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1646789668);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3501cadb-8a42-499d-ba20-2eb6e22bfbd8");
user_pref("toolkit.startup.last_success", 1656562377);
user_pref("toolkit.telemetry.cachedClientID", "6e4e0a91-6539-45aa-9fb7-450db6d90012");
user_pref("toolkit.telemetry.previousBuildID", "20220608170832");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
